Backup/eAd.Website/Controllers/ThemesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eAd.DataAccess;

namespace eAd.Website.Controllers
{
public class ThemesController : Controller
{
    private eAdDataContainer db = new eAdDataContainer();

    //
    // GET: /Themes/

    public ViewResult Index()
    {
        return View(db.Themes.ToList());
    }

    //
    // GET: /Themes/Details/5

    public ViewResult Details(long id)
    {
        Theme theme = db.Themes.Single(t => t.ThemeID == id);
        return View(theme);
    }

    //
    // GET: /Themes/Create

    public ActionResult Create()
    {
        return View();
    }

    //
    // POST: /Themes/Create

    [HttpPost]
    public ActionResult Create(Theme theme)
    {
        if (ModelState.IsValid)
        {
            db.Themes.AddObject(theme);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(theme);
    }

    //
    // GET: /Themes/Edit/5

    public ActionResult Edit(long id)
    {
        Theme theme = db.Themes.Single(t => t.ThemeID == id);

        var mystations = theme.Media.ToList();
        var otherStations = db.Media.ToList().Except(mystations);
        ViewBag.NonAddedMedia = new SelectList(otherStations, "MediaID", "Name");
        ViewBag.AddedMedia = new SelectList(mystations, "MediaID", "Name");
        return View(theme);
    }

    //
    // POST: /Themes/Edit/5

    [HttpPost]
    public ActionResult Edit(Theme theme)
    {
        if (ModelState.IsValid)
        {
            db.Themes.Attach(theme);
            db.ObjectStateManager.ChangeObjectState(theme, EntityState.Modified);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(theme);
    }

    //
    // GET: /Themes/Delete/5

    public ActionResult Delete(long id)
    {
        Theme theme = db.Themes.Single(t => t.ThemeID == id);
        return View(theme);
    }

    //
    // POST: /Themes/Delete/5

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(long id)
    {
        Theme theme = db.Themes.Single(t => t.ThemeID == id);
        db.Themes.DeleteObject(theme);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
        db.Dispose();
        base.Dispose(disposing);
    }

    public ActionResult RemoveMedia(long stationID, long groupID)
    {
        var grouping = db.Themes.Single(g => g.ThemeID == groupID);
        var station = grouping.Media.Where(s => s.MediaID == stationID).FirstOrDefault();
        if (station != null)
        {
            grouping.Media.Remove(station);
            db.SaveChanges();
            return Json(new { message = "Media Removed" }, JsonRequestBehavior.AllowGet);
        }
        else
        {
            return Json(new { message = "Media Does Not Exist" }, JsonRequestBehavior.AllowGet);
        }
    }

    public ActionResult AddMedia(long stationID, long groupID)
    {
        Theme theme = db.Themes.Single(g => g.ThemeID == groupID);
        var station = db.Media.Where(s => s.MediaID == stationID).FirstOrDefault();
        if (station != null)
        {
            theme.Media.Add(station);
            db.SaveChanges();
            return Json(new { message = "Media Added" }, JsonRequestBehavior.AllowGet);
        }
        else
        {
            return Json(new { message = "Media Does Not Exist" }, JsonRequestBehavior.AllowGet);
        }
    }
}
}

Backup/eAd.Website/Views/Themes/Create.cshtml
@model eAd.DataAccess.Theme

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Theme</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Backup/eAd.Website/Views/Themes/Delete.cshtml
@model eAd.DataAccess.Theme

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this category?</h3>
<fieldset>
    <legend>Theme</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Backup/eAd.Website/Views/Themes/Details.cshtml
@model eAd.DataAccess.Theme

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Theme</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ThemeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Backup/eAd.Website/Views/Themes/Edit.cshtml
@model eAd.DataAccess.Theme

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<link href="~/Content/themes/ui-lightness/jquery-ui-1.8.11.custom.css"/>
<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Category</legend>

        @Html.HiddenFor(model => model.ThemeID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="editor-label">
             <h3>Media: (@Model.Media.Count())</h3>
        </div>
        <table>
        <tr>
         <th>In Theme</th>
         <th>Not In Theme</th>
         </tr>
        <tr>
       
      <td id="InGroup" style="min-height:100;min-width:60">
      
      <div class="editor-field">
   
        <ul id="lstIn_Group">
        @foreach (var item in (IEnumerable<SelectListItem>)ViewBag.AddedMedia)
        {
            <li id="ns@(item.Value)" style="background-color: lightgray;margin-top:50" value="@(item.Value)"> @item.Text</li>
        }
        </ul>
        </div>
        
      
        </td>
      <td id="NotInGroup" style="min-height:100;min-width:60">
        <div class="editor-field">
       
          <ul id="lstNot_In_Group">
        @foreach (var item in (IEnumerable<SelectListItem>)ViewBag.NonAddedMedia)
        {
            <li id="ns@(item.Value)" style="background-color: lightgray;margin-top:50" value="@(item.Value)"> @item.Text</li>
        }
        </ul>
        
        </div>
        </td></tr>
        </table>
             
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

 <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            var source;
            var destination;
            var fn = function (event, ui) {
               
             
                $.ajax({
                    url: "@(Url.Action("AddMedia", "Themes", null, "http"))",
                    type: 'POST',
                    context: document.body,
                    data: { stationID: $(ui.draggable[0]).attr('value'), groupID: "@Model.ThemeID" },
                    success: function () {
                           $("#lstIn_Group").append($(ui.draggable[0]).removeAttr("style").attr("style", "background-color: lightgray;margin-top:50"));
                      
                    }
                });
                  $("#lstIn_Group li").draggable();
                    $("#lstNot_In_Group li").draggable();
            };
                var fn1 = function (event, ui) 
                {
                //                $("#lstNot_In_Group").append($(ui.draggable[0]).removeAttr("style"));
           
                      $.ajax({
                    url: "@(Url.Action("RemoveMedia", "Themes", null, "http"))",
                    type: 'POST',
                    context: document.body,
                    data: { stationID: $(ui.draggable[0]).attr('value'), groupID: "@Model.ThemeID" },
                    success: function () {
                             $("#lstNot_In_Group").append($(ui.draggable[0]).removeAttr("style").attr("style", "background-color: lightgray;margin-top:50"));
            
                 
                    }
                    
                });
                             $("#lstIn_Group li").draggable();
                    $("#lstNot_In_Group li").draggable();
            };

            $("#lstNot_In_Group li").draggable();
        
            $("#InGroup").droppable({ drop: fn });

            $("#lstIn_Group li").draggable(); // { helper: 'clone' } not good
            $("#NotInGroup").droppable({ drop: fn1 });
//            $("#basket").click(function () {
//                var textArray = $.map($("#lstIn_Group li"),
//                    function (item) {
//                        return $(item).text();
//                    });
//            });
        });
    </script>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Backup/eAd.Website/Views/Themes/Index.cshtml
@model IEnumerable<eAd.DataAccess.Theme>

@{
    ViewBag.Title = "Index";
}

<h2>Media Categories</h2>

<p>
    @Html.ActionLink("Add New Category", "Create")
</p>
<table>
    <tr>
        <th>
            Name
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ThemeID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ThemeID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ThemeID })
        </td>
    </tr>
}

</table>