eAd.Website/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImageUploadAndCrop.Models;
using eAd.DataAccess;
using eAd.DataViewModels;
using eAd.Utilities;
using eAd.Website.Extensions;
using eAd.Website.Repositories;

namespace eAd.Website.Controllers
{
public class MediaController : Controller
{
    private readonly eAdEntities _db = new eAdEntities();

    //
    // GET: /Default1/

    public ViewResult Index()
    {
        return View(_db.Media.ToList());
    }

    //
    // GET: /Default1/Details/5

    public ViewResult Details(long id)
    {
        Medium medium = _db.Media.Single(m => m.MediaID == id);
        return View(medium);
    }

    private readonly string[] _types = new string[]
                                 {
                                     "Video",
                                     "Powerpoint", "Image", "Flash",
                                     "Marquee"
                                 };
    //
    // GET: /Default1/Create

    public ActionResult Create()
    {
        UploadRepository.CreateUploadGUID(HttpContext);
        var medium = new Medium {Duration = TimeSpan.Zero};
        ViewBag.MediaType = new SelectList(_types.Distinct().ToList(), "", "");
        return View(medium);
    }


   //
    // GET: /Default1/Create
    public ActionResult CreateVideo(string uploadid, string type, string thumbnail, string text, string path, string duration, string originalFileName)
    {
        var medium = new Medium { Duration = TimeSpan.Zero };
        medium.Duration = TimeSpan.Parse(duration);
        medium.Location = path;
        medium.Type = type;
        medium.ThumbnailUrl = thumbnail;
        medium.Name = Path.GetFileNameWithoutExtension(originalFileName).Replace("-", " ").Replace("_", " ");
        return View(medium);
    }
    [HttpPost]
    public ActionResult CreateVideo(Medium medium)
    {
        return Create(medium);
    }
      //
    // GET: /Default1/Create
    public ActionResult CreateFlash(string uploadid, string type, string thumbnail, string text, string path, string duration, string originalFileName)
    {
        var medium = new Medium { Duration = TimeSpan.Zero };
        medium.Duration = TimeSpan.Parse(duration);
        medium.Location = path;
        medium.Type = type;
        medium.ThumbnailUrl = thumbnail;
        medium.Name = Path.GetFileNameWithoutExtension(originalFileName).Replace("-", " ").Replace("_", " ");
        return View(medium);
    }

    [HttpPost]
    public ActionResult CreateFlash(Medium medium)
    {
     return  Create(medium);
    }
     //
    // GET: /Default1/Create
    public ActionResult CreatePicture(string uploadid, string type, string thumbnail, string text, string path, string duration, string originalFileName)
    {
        var medium = new Medium { Duration = TimeSpan.Zero };
        medium.Duration = TimeSpan.Parse(duration);
        medium.Location = path;
        medium.Type = type;
        medium.ThumbnailUrl = thumbnail;
        medium.Name = Path.GetFileNameWithoutExtension(originalFileName).Replace("-", " ").Replace("_", " ");
        return View(medium);
    }

    [HttpPost]
    public ActionResult CreatePicture(Medium medium)
    {
        return Create(medium);
    }

    //
    // GET: /Default1/Create
    public ActionResult CreatePowerpoint(string uploadid, string type, string thumbnail, string text, string path, string duration, string originalFileName)
    {
        var medium = new Medium { Duration = TimeSpan.Zero };
        medium.Duration = TimeSpan.Parse(duration);
        medium.Location = path;
        medium.Type = type;
        medium.ThumbnailUrl = thumbnail;
        medium.Name = Path.GetFileNameWithoutExtension(originalFileName).Replace("-", " ").Replace("_"," ");
        return View(medium);
    }

    [HttpPost]
    public ActionResult CreatePowerpoint(Medium medium)
    {
        return Create(medium);
    }

    //
    // GET: /Default1/Create
    public ActionResult CreateMarquee(string uploadid, string type, string thumbnail, string text, string path, string duration, string originalFileName)
    {
     
        var medium = new Medium { Duration = TimeSpan.Zero };
        medium.Duration = TimeSpan.Parse(duration);
        medium.Location = path;
        medium.Type = type;
        medium.ThumbnailUrl = thumbnail;
        medium.Name = Path.GetFileNameWithoutExtension(originalFileName).Replace("-", " ").Replace("_", " ");
        ViewBag.ForeColor = "000000";
        ViewBag.BackColor = "FFFFFF";
        return View(medium);
    }
    [HttpPost]
    public ActionResult CreateMarquee(Medium medium, string foreColor,string backColor)
    {
        medium.Options = "foreColor=" + foreColor + ";backColor=" + backColor;
        return Create(medium);
    }
    //public ActionResult Picker(string name, string type)
    //{
    //   var media =  _db.Media
    //    return View();
    //}

    public ActionResult Picker(string componentId, float width, float height)
    {

        ViewBag.Types = new SelectList(_db.Media.Select(m => m.Type).Distinct().ToList(), "", "");
        ViewBag.Themes = new SelectList(_db.Themes.Select(m => m.Name).Distinct().ToList(), "", "");
        ViewBag.ComponentId = componentId;
        ViewBag.Width = width;
        ViewBag.Height = height;
   
        var media = _db.Media.ToList();


          List<MediaListModel> mediaList = new List<MediaListModel>();
          foreach (var medium in media)
          {
              try
              {
                  var model = medium.CreateModel();
                  mediaList.Add(model);
              }
              catch (Exception)
              {


              }
          }
        return View(mediaList);

        //var aString = "";

        //foreach (var VARIABLE in ViewBag.Types)
        //{
        //    aString += VARIABLE;
        //}

        //foreach (var VARIABLE in ViewBag.Themes)
        //{
        //    aString += VARIABLE;
        //}

        //foreach (var VARIABLE in media)
        //{
        //    aString += VARIABLE.Name;
        //}
        //return Content(aString);
    }

    public ActionResult PickerList(string name, string type, string theme="")
    {
        var types = _db.Media.Distinct().ToList();
        ViewBag.Types = new SelectList(types.Select(t=>t.Type), "", "");
        var media = _db.Media.ToList();

        if (!String.IsNullOrEmpty(name))
        {
            media = new List<Medium>(media.Where(n => n.Name.ToLower().Contains(name.ToLower())));
        }

        if (!String.IsNullOrEmpty(type))
        {
            media = new List<Medium>(media.Where(n => n.Type.ToLower().Contains(type.ToLower())));
        }

        if (!String.IsNullOrEmpty(theme))
        {
            media = new List<Medium>(media.Where(n => 
                n.Themes.Where(t=>t.Name.ToLower().Contains(type.ToLower())).Count()>0)
                );
        }

        List<MediaListModel> mediaList = new List<MediaListModel>(); 
        foreach (var medium in media)
        {
            try
            {
  var model = medium.CreateModel();
            mediaList.Add(model);
            }
            catch (Exception)
            {
                
              
            }
          
        }
      //  var mediaList = media.Select(m => m.CreateModel()).ToList();

        return View(mediaList);
        var aString = "";
        foreach (var VARIABLE in media)
        {
             aString += VARIABLE.Name;
        }
        
       // return Content(aString);
    }

    //
    // POST: /Default1/Create

    [HttpPost]
    public ActionResult Create(Medium medium)
    {
        if (ModelState.IsValid)
        {
            medium.Created = DateTime.Now;
            _db.Media.AddObject(medium);
            _db.SaveChanges();
            UploadedContent upload;

            var   location = UploadRepository.GetFileUrl(this.HttpContext, medium.MediaID.ToString(CultureInfo.InvariantCulture),
                             medium.MediaID.ToString(CultureInfo.InvariantCulture), UploadType.Media, out upload);


            if (upload != null)
            {
                if (medium.Duration == TimeSpan.Zero)
                {
                    medium.Duration = new TimeSpan(upload.Duration.Ticks);
                }
                else
                {

                }
            }

            if (location != null && location[0] != null)
            {
                medium.Location = location[0];
                using(var fs = new FileStream(Server.MapPath("~/"+location[0]),FileMode.Open,FileAccess.Read,FileShare.ReadWrite))
                {
                    medium.Hash = Hashes.MD5(fs);
                }
                if(location.Length>1)
                {
                    medium.ThumbnailUrl = location[1];
                }

            }


            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(medium);
    }

    //
    // GET: /Default1/Edit/5

    public ActionResult Edit(long id)
    {
        UploadRepository.CreateUploadGUID(HttpContext);
        Medium medium = _db.Media.Single(m => m.MediaID == id);
        if(medium.Duration==null)
            medium.Duration = TimeSpan.Zero;
        medium.Updated = DateTime.Now;
        bool shouldCalculatenewHash = medium.Hash == null || medium.Size == 0;

        // Calculate new hash/size
        if (shouldCalculatenewHash)
        {


eAd.Website/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eAd.Utilities;
using eAd.Website.CustomControls;
using eAd.Website.Extensions;
using eAd.Website.Repositories;
using irio.mvc.fileupload;

namespace eAd.Website.Controllers
{

public class UploadController : Controller
{
    private UploadType _type = UploadType.Media;
    private string _currentMedia = "";
    string _path
    {
        get
        {
            return HttpContext.Request.Url.Scheme + "://" + HttpContext.Request.Url.Authority + HttpContext.Request.ApplicationPath;
        }
    }



    // [Authorize]
    public ActionResult Index(string MediaId, UploadType type)
    {
        switch (type)
        {
        case UploadType.Media:
            ViewBag.Name = "MediaUploadForm";
            break;

        default:
            ViewBag.Name = "MediaUploadForm";
            break;
        }
        ViewBag.autoUpload = true;
        ViewBag.multiple = false;
        ViewBag.Type = _type;
        _type = type;

        if (HttpContext.Session != null)
            _currentMedia = (string)HttpContext.Session["CurrentMedia"];
        //if (HttpContext.Session != null)
        //    HttpContext.Session["CurrentMedia"] = MediaId;

        return View();
    }


    /// <summary>
    /// Upload a file and return a JSON result
    /// </summary>
    /// <param name="file">The file to upload.</param>
    /// <param name="fileCollection"></param>
    /// <param name="type"> type of upload</param>
    /// <returns>a FileUploadJsonResult</returns>
    /// <remarks>
    /// It is not possible to upload files using the browser's XMLHttpRequest
    /// object. So the jQuery Form Plugin uses a hidden iframe element. For a
    /// JSON response, a ContentType of application/json will cause bad browser
    /// behavior so the content-type must be text/html. Browsers can behave badly
    /// if you return JSON with ContentType of text/html. So you must surround
    /// the JSON in textarea tags. All this is handled nicely in the browser
    /// by the jQuery Form Plugin. But we need to overide the default behavior
    /// of the JsonResult class in order to achieve the desired result.
    /// </remarks>
    /// <seealso cref="http://malsup.com/jquery/form/#code-samples"/>
    //     [Authorize]
    public FileUploadJsonResult AjaxUpload(IEnumerable<HttpPostedFileBase> fileCollection, UploadType type, string uploadPath)
    {


        _type = type;
        // TODO: Add your business logic here and/or save the file
        //System.Threading.Thread.Sleep(2000); // Simulate a long running upload
        // Some browsers send file names with full path. This needs to be stripped.


        //string physicalPath = PathForUpload(file.FileName, 0);


        //// The files are not actually saved in this demo
        //file.SaveAs(physicalPath);
        //lastSavedFile.Add(ResolvePath(physicalPath));
        foreach (string file in Request.Files)
        {
            var postedFile = Request.Files[file];
            string thumbPath;
            TimeSpan aduration;
            string filetype;
            UploadRepository.StoreMediaTemp(HttpContext, postedFile, _type, out thumbPath, out uploadPath, out aduration, out filetype);
            // Return JSON
            if (postedFile != null)
            {
                if (Request.Url != null)
                {
                    var result=new FileUploadJsonResult
                    {
                        Data =
                        new
                        {
                            message =
                            string.Format("Uploaded {0} successfully.", postedFile.FileName),
                            thumbnail = _path +"/"+ thumbPath.Replace(Request.ServerVariables["APPL_PHYSICAL_PATH"], String.Empty),
                            type = !String.IsNullOrEmpty(filetype)?filetype : MimeExtensionHelper.FindMime(uploadPath, true),
                            text = MimeExtensionHelper.FindMime(uploadPath, true).Contains("text") ? thumbPath : "",
                            path = uploadPath.Replace(Request.ServerVariables["APPL_PHYSICAL_PATH"], String.Empty),
                            originalFileName = postedFile.FileName,
                            duration = aduration.ToString()
                        }
                    };
                    return result;
                }
            }
        }



        return new FileUploadJsonResult { Data = new { message = "Upload Failed" } };


    }


    public FileUploadJsonResult AjaxUploadStatus(string ID)
    {

        ID = FileUpload.UploadIDTag +ID;

        return new FileUploadJsonResult { Data = UploadManager.GetStatus(ID), JsonRequestBehavior = JsonRequestBehavior.AllowGet };

    }



    //public ActionResult Save(IEnumerable<HttpPostedFileBase> attachments)
    //{
    //    List<string > lastSavedFile = new List<string>();
    //    // The Name of the Upload component is "attachments"
    //    foreach (HttpPostedFileBase file in attachments)
    //    {
    //        // Some browsers send file names with full path. This needs to be stripped.


    //        //string physicalPath = PathForUpload(file.FileName, 0);


    //        //// The files are not actually saved in this demo
    //        //file.SaveAs(physicalPath);
    //        //lastSavedFile.Add(ResolvePath(physicalPath));

    //       string physicalPath= ResizePicture(file);
    //        string thumbPath= ResizePictureThumb(file);
    //        if(physicalPath!=null)
    //       lastSavedFile.Add(UploadRepository.ResolvePath(this.HttpContext,physicalPath));
    //        lastSavedFile.Add(UploadRepository.ResolvePath(this.HttpContext, thumbPath));

    //    }

    //    if (HttpContext.Session != null)
    //        HttpContext.Session["SavedFileList"] = lastSavedFile;
    //    // Return an empty string to signify success
    //    return Content("");
    //}



    //    [Authorize]
    public ActionResult Remove(string[] fileNames)
    {
        // The parameter of the Remove action must be called "fileNames"


        foreach (string fullName in fileNames)
        {
            // string physicalPath = PathForUpload(fullName,0);
            // TODO: Verify user permissions

            //    if (System.IO.File.Exists(physicalPath))
            {
                // The files are not actually removed in this demo
                // System.IO.File.Delete(physicalPath);
            }
        }

        // Return an empty string to signify success
        return Content("");
    }
}
}


eAd.Website/Views/Shared/DialogBox.cshtml
@model eAd.Website.CustomControls.DialogBox

@{
    ViewBag.Title = "Error";
}

<h2>
@Model.Title
</h2>

@Model.Message

eAd.Website/Views/Shared/FileUpload.cshtml
@using eAd.Website.CustomControls
@model eAd.Website.CustomControls.FileUpload

@{
    ViewBag.Title = "Error";
}
<script src="@Url.Content("~/Scripts/jquery.form.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.blockUI.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $("#@(Model.Name+ "-Form")").ajaxForm({
            iframe: true,
            dataType: "json",
            beforeSubmit: function () {
                $("#@(Model.Name+ "-Form")").block({ message: '<h1><img src="@Url.Content("~/Content/busy.gif")" /> Uploading file...</h1>' });
                
                // Start Progress Monitoring
               var  intervalID = window.setInterval(function(){
                 
                  $.ajax({
        type: "AJAX",
        url: "@Url.Action("AjaxUploadStatus","Upload", new {ID=Model.UploadID.Replace(FileUpload.UploadIDTag,"")})",
        data: null,
        success: function (data) {
            $("#Status").val(data);
//             var e = executor.get_xml().documentElement;                   
//                        var empty = e.getAttribute('empty');
//                    
//                        if(!empty){
//                            var percent = e.getAttribute('progress');
//                            var file = e.getAttribute('file');
//                            var kbs = Math.round(parseInt(e.getAttribute('bytes')) / 1024);    
//                            var size = Math.round(parseInt(e.getAttribute('size')) / 1024);                        
//                        
//                            //  update the progressbar to the new value
//                            progressBar.set_percentage(percent);
//                            //  upadte the message
//                            updateMessage('info', 'Uploading ' + file + ' ... ' + kbs + ' of ' + size + ' KB');
//                            
//                            if(percent == 100){
//                                //  clear the interval
//                                window.clearInterval(intervalID);                        
//                            }                        
        },
        dataType: "json",
        traditional: true,
        contentType: 'application/json; charset=utf-8'
    });
    }, 500);



            }, success: function (result) {
                $("#@(Model.Name+ "-Form")").unblock();
                $("#@(Model.Name+ "-Form")").resetForm();
                $.growlUI('Upload Status', result.message);
                $("#@(Model.Name+ "-Preview")").attr("src", result.thumbnail);
                @{
                if(!String.IsNullOrEmpty(Model.OnComplete))
                {
                    <text> @Model.OnComplete (result); </text>;
                }
                }
             }, error: function (xhr, textStatus, errorThrown) {
                $("#@(Model.Name+ "-Form")").unblock();
                $("#@(Model.Name+ "-Form")").resetForm();
                $.growlUI(null, 'Error uploading file');
            }
        });
    });
</script>
<form action="@Model.Action"
      enctype="multipart/form-data" id="@(Model.Name+ "-Form")" method="post">
    <fieldset>
        <legend>@Model.Title</legend>
        <label>@Model.Label <input name="@(Model.Name+ "-Uploader")" 
                                   onchange='document.getElementById("@(Model.Name+ "-SubmitButton")").click();' type="file" />
                                   (@Model.MaxFileSize Max Upload Size)
           
            <input id="@(Model.Name+ "-SubmitButton")" 
                   style="display:none" type="submit" value="Upload"/>
            <input id="Status" type="text"></input>
            <br/>
            </label>
        <img alt=" " id="@(Model.Name+ "-Preview")" src="@Url.Content("~/Content/check48.png")"/>
        <input name="@string.Format("{0}-UploadID", Model.Name)" type="hidden" value="@Model.UploadID"/>
    </fieldset>
</form>

eAd.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
     <link href="@Url.Content("~/Content/themes/ui-lightness/jquery-ui-1.8.11.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
   
<script src="@Url.Content("~/Scripts/jquery-ui.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>GreenCore Online</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                   @* <li>@Html.ActionLink("About", "About", "Home")</li>*@
                       <li>@Html.ActionLink("Station Summary", "List", "Station")</li>
                         <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                                          <li>@Html.ActionLink("Themes", "Index", "Themes")</li>
                        <li>@Html.ActionLink("Media Library", "Index", "Media")</li>
                        
                               <li>@Html.ActionLink("Groupings", "Index", "Grouping")</li>

                                   <li>@Html.ActionLink("Mosaic", "Index", "Mosaic")</li>
                            <li>@Html.ActionLink("Stations", "Index", "Stations")</li>
                    
                           
                                  <li>@Html.ActionLink("Messages", "Index", "Messages")</li>
                                      <li>@Html.ActionLink("Cars", "Index", "Cars")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>


eAd.Website/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}