Backup/eAd.Website/Controllers/StationController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.Services.Description;
using eAd.DataViewModels;
using eAd.Website.eAdDataService;
//using MessageViewModel = eAd.Website.eAdDataService;


namespace eAd.Website.Controllers
{
public class StationController : Controller
{
    private ServiceClient _service;
    private ServiceClient Service
    {
        get
        {

            if (_service == null)
            {
                _service = new ServiceClient();
                if (HttpContext.Request.UserHostAddress != "1.9.13.61")
                {
                    _service.ClientCredentials.Windows.ClientCredential.UserName = "admin";
                    _service.ClientCredentials.Windows.ClientCredential.Password = "Green2o11";
                }
            }
            return _service;
        }
    }

    // GET: /Station/

    public ActionResult Index()
    {
        return View();
    }

    //
    // GET: /Station/

    public ActionResult List()
    {
        Response.AddHeader("Refresh", "10");
        ViewBag.StationsCount = Service.GetAllStations().Count();
        ViewBag.StationsOnlineCount = Service.GetOnlineStations().Count();
        ViewBag.StationSummary = Service.GetAllStations();
        MessageViewModel firstOrDefault = Service.GetAllMyMessages(1).OrderByDescending(m => m.ID).FirstOrDefault();
        if (firstOrDefault != null)
        {
            ViewBag.LastMessage = firstOrDefault.Text + "(1/" + Service.GetAllMyMessages(1).Count() + ")";
        }
        return View();
    }
    //
    // GET: /Station/Details/5

    public ActionResult Details(int id)
    {
        return View();
    }

    //
    // GET: /Station/Create

    public ActionResult Create()
    {
        return View();
    }

    //
    // POST: /Station/Create

    [HttpPost]
    public ActionResult Create(FormCollection collection)
    {
        try
        {
            // TODO: Add insert logic here

            return RedirectToAction("Index");
        }
        catch
        {
            return View();
        }
    }

    //
    // GET: /Station/Edit/5

    public ActionResult Edit(int id)
    {
        return View();
    }

    //
    // POST: /Station/Edit/5

    [HttpPost]
    public ActionResult Edit(int id, FormCollection collection)
    {
        try
        {
            // TODO: Add update logic here

            return RedirectToAction("Index");
        }
        catch
        {
            return View();
        }
    }

    //
    // GET: /Station/Delete/5

    public ActionResult Delete(int id)
    {
        return View();
    }

    //
    // POST: /Station/Delete/5

    [HttpPost]
    public ActionResult Delete(int id, FormCollection collection)
    {
        try
        {
            // TODO: Add delete logic here

            return RedirectToAction("Index");
        }
        catch
        {
            return View();
        }
    }

    public ActionResult Engage(long stationID, string rfidCode)
    {
        //var station = Service.GetAllStations().Where(s=>s.StationID ==stationID).FirstOrDefault();
        // if(station!=null)
        // {
        //  station.Available = false;
        Service.MakeStationUnAvailable(stationID, rfidCode);
        //  }
        return RedirectToAction("List");
    }

    public ActionResult DisEngage(long stationID)
    {
        Service.MakeStationAvailable(stationID);
        return RedirectToAction("List");
    }

    public ActionResult Screenshot(long stationID)
    {
        Service.CaptureScreenShot(stationID);
        return RedirectToAction("ShowScreenShot", new  {stationID=stationID});
    }

    public ActionResult ShowScreenShot(long stationID)
    {
        Response.AddHeader("Refresh", "5");
        ViewBag.StationID = stationID;
        return View();
    }
}
}

Backup/eAd.Website/Controllers/StationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eAd.DataAccess;
using eAd.Website.Repositories;
using irio.utilities;

namespace eAd.Website.Controllers
{
public class StationsController : Controller
{
    private eAdDataContainer db = new eAdDataContainer();

    //
    // GET: /Stations/

    public ViewResult Index()
    {
        try
        {
            return View(db.Stations.ToList());
        }
        catch (Exception exception)
        {
            ViewBag.Status = ("Opps " + exception.GetType() + "\n" + exception.Message + "\n" + exception.StackTrace + "\n" + ((exception.InnerException != null) ? exception.InnerException.Message : "").Replace("\n", "</br>"));

        }
        return View();
    }

    //
    // GET: /Stations/Details/5

    public ViewResult Details(long id)
    {
        Station station = db.Stations.Single(s => s.StationID == id);
        return View(station);
    }

    //
    // GET: /Stations/Create

    public ActionResult Create()
    {
        return View();
    }

    //
    // POST: /Stations/Create

    [HttpPost]
    public ActionResult Create(Station station)
    {
        if (ModelState.IsValid)
        {
            db.Stations.AddObject(station);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(station);
    }

    //
    //
    // GET: /Stations/UploadScreenshot/5
    public ActionResult UploadScreenshot(long id)
    {
        ViewBag.StationID = id;
        return View();
    }
    //
    //
    // GET: /Stations/UploadScreenshot/5
    [HttpPost]
    public ActionResult UploadScreenshot(long stationID,HttpPostedFileBase file)
    {
        if (file.ContentLength > 0)
        {
            //     var fileName = Path.GetFileName(file.FileName);
            var path = Path.Combine(Server.MapPath("~/ScreenShots/"+stationID+"/"), "shot.jpg");
            if (FileUtilities.FileExists(path))
                new FileInfo(path).Delete();
            FileUtilities.SaveStream(file.InputStream, path, false);

        }

        //   UploadedContent upload;


        //var location = UploadRepository.GetFileUrl(this.HttpContext, medium.MediaID.ToString(),
        //                                           medium.MediaID.ToString(), UploadType.Media, out upload);

        //if (upload != null)
        //{
        //    if (medium.Duration == TimeSpan.Zero)
        //    {
        //        medium.Duration = new TimeSpan(upload.Duration.Ticks);
        //    }
        //    else
        //    {

        //    }
        //}

        //if (location != null)
        //    medium.DisplayLocation = location;
        return RedirectToAction("Index");
    }

    //
    //
    // GET: /Stations/Edit/5

    public ActionResult Edit(long id)
    {
        Station station = db.Stations.Single(s => s.StationID == id);


        return View(station);
    }

    //
    // POST: /Stations/Edit/5

    [HttpPost]
    public ActionResult Edit(Station station)
    {
        if (ModelState.IsValid)
        {
            db.Stations.Attach(station);
            db.ObjectStateManager.ChangeObjectState(station, EntityState.Modified);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(station);
    }

    //
    // GET: /Stations/Delete/5

    public ActionResult Delete(long id)
    {
        Station station = db.Stations.Single(s => s.StationID == id);
        return View(station);
    }

    //
    // POST: /Stations/Delete/5

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(long id)
    {
        Station station = db.Stations.Single(s => s.StationID == id);

        //Delete Messages
        List<object> stuffToDelete = new List<object>(); 
        foreach (var message in station.Messages)
        {
            stuffToDelete.Add(message);
        }

        foreach (var o in stuffToDelete)
        {
            db.Messages.DeleteObject(o as Message);
        }

        stuffToDelete.Clear();

        foreach (var message in station.Groupings)
        {
            stuffToDelete.Add(message);
        }

        foreach (var group in stuffToDelete)
        {
            (group as Grouping).Stations.Remove(station);
        }

        stuffToDelete.Clear();

     db.Stations.DeleteObject(station);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
        db.Dispose();
        base.Dispose(disposing);
    }
}
}

Backup/eAd.Website/Views/Station/List.cshtml
@using System.Collections
@using eAd.DataViewModels
@using eAd.Website.eAdDataService
@*@using StationViewModel = eAd.Website.eAdDataService.StationViewModel*@
<h2> Station Summary </h2>
Number Of Stations Deployed:  <b>@ViewBag.StationsCount</b> <br/>
Number Of Stations Online:  <b>@ViewBag.StationsOnlineCount</b><br/>
<br/>
@{
    var summary = (IEnumerable<StationViewModel>)ViewBag.StationSummary;
}
<table>
<tr>
<td>Name &nbsp;&nbsp;</td>
<td>Last CheckIn &nbsp;&nbsp;</td>
<td>Last Status</td>
<td>Online &nbsp;&nbsp;</td>
<td>Available &nbsp;&nbsp;</td>
<td>Map &nbsp;&nbsp;</td>
<td colspan="2">Actions &nbsp;&nbsp;</td>
</tr>
  
@foreach (var station in summary)
{ 
    <tr>

    <td>@station.Name &nbsp;&nbsp;</td>
<td>@(station.LastCheckIn!=null?station.LastCheckIn.ToString():"Never") &nbsp;&nbsp;</td>
<td>@(station.Status)</td>
<td>@(station.IsOnline?"Yes":"No") &nbsp;&nbsp;</td>
<td>@(station.Available?"Yes":"No") &nbsp;&nbsp;</td>
<td>   @Html.ActionLink("Map", "Index", "Map", new { stationID = station.StationID }, new { @class = "mapLink" })</td>
     <td>
     <input type="button" value="Engage" name="Engage" onclick="Engage@(station.StationID)()"/>
   @*  @Html.ActionLink("Engage", "Engage", "Station", new { stationID = station.StationID }, new { onlick = "Engage"+@station.StationID+"();" })*@
     <input type="text" id="RFID@(station.StationID)" value="1" /><br />
     <script type="text/javascript">
   function Engage@(station.StationID)()
    {
       $.ajax({
  type: 'POST',
  url: "/Station/Engage",
  data: { stationID: "@(station.StationID)", rfidCode: $("#RFID@(station.StationID)").val() }
 
});
     
    }
   </script>
     </td>
     <td>@Html.ActionLink("DisEngage", "DisEngage", "Station", new { stationID = station.StationID }, null)</td>
      <td>@Html.ActionLink("Screenshot", "Screenshot", "Station", new { stationID = station.StationID }, null)
    
      </td>
    </tr>
}
</table>

<br/>
Last Sent Message: @ViewBag.LastMessage

Backup/eAd.Website/Views/Station/ShowScreenShot.cshtml
@model object

@{
    Layout = null;
}
  <img alt="No Image" src="@(Url.Content("~/ScreenShots/" + ViewBag.StationID + "/shot.jpg"))"/>