Backup/eAd.Website/Controllers/GroupingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eAd.DataAccess;
using eAd.DataViewModels;
using eAd.Website.eAdDataService;
//using MessageViewModel = eAd.Website.eAdDataService.MessageViewModel;

namespace eAd.Website.Controllers
{
public class GroupingController : Controller
{
    private eAdDataContainer db = new eAdDataContainer();

    private ServiceClient _service;
    private ServiceClient Service
    {
        get
        {

            if (_service == null)
            {
                _service = new ServiceClient();
                //   if (HttpContext.Request.UserHostAddress != "1.9.13.61")
                //{
                //    _service.ClientCredentials.Windows.ClientCredential.UserName = "admin";
                //    _service.ClientCredentials.Windows.ClientCredential.Password = "Green2o11";
                //}
            }
            return _service;
        }
    }

    //
    // GET: /Grouping/

    public ViewResult Index()
    {
        return View(db.Groupings.ToList());
    }

    //
    // GET: /Grouping/Details/5

    public ViewResult Details(long id)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == id);
        return View(grouping);
    }

    //
    // GET: /Grouping/Create

    public ActionResult Create()
    {
        return View();
    }

    //
    // POST: /Grouping/Create

    [HttpPost]
    public ActionResult Create(Grouping grouping)
    {
        if (ModelState.IsValid)
        {
            grouping.MosaicID = 1;
            db.Groupings.AddObject(grouping);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(grouping);
    }

    //
    // GET: /Grouping/Edit/5

    public ActionResult Edit(long id)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == id);
        var mystations = grouping.Stations.ToList();
        var otherStations = db.Stations.ToList().Except(mystations);

        var mythemes = grouping.Themes.ToList();
        var otherThemes = db.Themes.ToList().Except(mythemes);
        ViewBag.NonAddedStations = new SelectList(otherStations, "StationID", "Name");
        ViewBag.AddedStations = new SelectList(mystations, "StationID", "Name");

        ViewBag.NonAddedThemes = new SelectList(otherThemes, "ThemeID", "Name");
        ViewBag.AddedThemes = new SelectList(mythemes, "ThemeID", "Name");


        ViewBag.MosaicID = new SelectList(db.Mosaics, "MosaicID", "Name", grouping.MosaicID);

        return View(grouping);
    }


    public JsonResult AddStation(long stationID, long groupID)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == groupID);
        var station = db.Stations.Where(s => s.StationID == stationID).FirstOrDefault();
        if (station != null)
        {
            grouping.Stations.Add(station);
            db.SaveChanges();

            var message = new MessageViewModel();
            message.Command = "Joined Group";
            message.Type = "Group";
            //   message.UserID =
            message.Text = groupID.ToString();
            Service.SendMessageToStation(stationID, message);

            return Json(new {message = "Station Added"},JsonRequestBehavior.AllowGet);
        }
        else
        {
            return Json(new { message=  "Station Does Not Exist"},JsonRequestBehavior.AllowGet);
        }

    }
    public JsonResult RemoveStation(long stationID, long groupID)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == groupID);
        var station = grouping.Stations.Where(s => s.StationID == stationID).FirstOrDefault();
        if (station != null)
        {
            grouping.Stations.Remove(station);
            db.SaveChanges();

            var message = new MessageViewModel();
            message.Command = "Left Group";
            message.Type = "Group";
            //   message.UserID =
            message.Text = groupID.ToString();
            Service.SendMessageToStation(stationID, message);
            return Json(new { message = "Station Removed" }, JsonRequestBehavior.AllowGet);
        }
        else
        {
            return Json(new { message = "Station Does Not Exist" }, JsonRequestBehavior.AllowGet);
        }

    }
    //
    // POST: /Grouping/Edit/5

    [HttpPost]
    public ActionResult Edit(Grouping grouping)
    {
        if (ModelState.IsValid)
        {
            db.Groupings.Attach(grouping);
            db.ObjectStateManager.ChangeObjectState(grouping, EntityState.Modified);
            db.SaveChanges();


            var message = new MessageViewModel();
            message.Command = "Updated Mosaic";
            message.Type = "Media";

            message.Text = grouping.Name;
            Service.SendMessageToGroup(grouping.GroupingID, message);

            return RedirectToAction("Index");
        }
        ViewBag.MosaicID = new SelectList(db.Mosaics, "MosaicID", "Name", grouping.MosaicID);
        return View(grouping);
    }

    //
    // GET: /Grouping/Delete/5

    public ActionResult Delete(long id)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == id);
        return View(grouping);
    }

    //
    // POST: /Grouping/Delete/5

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(long id)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == id);
        db.Groupings.DeleteObject(grouping);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
        db.Dispose();
        base.Dispose(disposing);
    }

    public ActionResult AddTheme(long stationID, long groupID)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == groupID);
        var theme = db.Themes.Where(s => s.ThemeID == stationID).FirstOrDefault();
        if (theme != null)
        {
            grouping.Themes.Add(theme);
            db.SaveChanges();
            var message = new MessageViewModel();
            message.Command = "Added Theme";
            message.Type = "Media";
            //   message.UserID =
            message.Text = theme.ThemeID.ToString();
            Service.SendMessageToGroup(groupID, message);
            return Json(new { message = "Station Added" }, JsonRequestBehavior.AllowGet);
        }
        else
        {
            return Json(new { message = "Station Does Not Exist" }, JsonRequestBehavior.AllowGet);
        }
    }

    public ActionResult RemoveTheme(long stationID, long groupID)
    {
        Grouping grouping = db.Groupings.Single(g => g.GroupingID == groupID);
        var theme = grouping.Themes.Where(s => s.ThemeID == stationID).FirstOrDefault();
        if (theme != null)
        {
            grouping.Themes.Remove(theme);
            db.SaveChanges();
            var message = new MessageViewModel();
            message.Command = "Removed Theme";
            message.Type = "Media";
            //   message.UserID =
            message.Text = theme.ThemeID.ToString();
            Service.SendMessageToGroup(groupID, message);
            return Json(new { message = "Station Removed" }, JsonRequestBehavior.AllowGet);
        }
        else
        {
            return Json(new { message = "Station Does Not Exist" }, JsonRequestBehavior.AllowGet);
        }
    }
}
}

Backup/eAd.Website/Views/Grouping/Create.cshtml
@model eAd.DataAccess.Grouping

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Grouping</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Backup/eAd.Website/Views/Grouping/Delete.cshtml
@model eAd.DataAccess.Grouping

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Grouping</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Backup/eAd.Website/Views/Grouping/Details.cshtml
@model eAd.DataAccess.Grouping

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Grouping</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.GroupingID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Backup/eAd.Website/Views/Grouping/Edit.cshtml
@using eAd.DataAccess
@model eAd.DataAccess.Grouping

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<link href="~/Content/themes/ui-lightness/jquery-ui-1.8.11.custom.css"/>
<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Group:  @(Model.Name) </legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MosaicID, "Mosaic")
        </div>
        <div class="editor-field">
            @Html.DropDownList("MosaicID", String.Empty)
            @Html.ValidationMessageFor(model => model.MosaicID)
        </div>


        @Html.HiddenFor(model => model.GroupingID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
      

        <div class="editor-label">
             <h3>Stations: (@Model.Stations.Count())</h3>
        </div>
        <table>
        <tr>
         <th>In Group</th>
         <th>Not In Group</th>
         </tr>
        <tr>
       
      <td id="InGroup" style="min-height:100;min-width:60">
      
      <div class="editor-field">
   
        <ul id="lstIn_Group">
        @foreach (var item in (IEnumerable<SelectListItem>)ViewBag.AddedStations)
        {
            <li id="ns@(item.Value)" style="background-color: lightgray;margin-top:50" value="@(item.Value)"> @item.Text</li>
        }
        </ul>
        </div>
        
      
        </td>
      <td id="NotInGroup" style="min-height:100;min-width:60">
        <div class="editor-field">
       
          <ul id="lstNot_In_Group">
        @foreach (var item in (IEnumerable<SelectListItem>)ViewBag.NonAddedStations)
        {
            <li id="ns@(item.Value)" style="background-color: lightgray;margin-top:50" value="@(item.Value)"> @item.Text</li>
        }
        </ul>
        
        </div>
        </td></tr>
        </table>
             
        
       @*  <div class="editor-label">
             <h3>Themes: (@Model.Themes.Count())</h3>
        </div>
        <table>
        <tr>
         <th>In Group</th>
         <th>Not In Group</th>
         </tr>
        <tr>
       
      <td id="ThemeInGroup" style="min-height:100;min-width:60">
      
      <div class="editor-field">
   
        <ul id="ThemelstIn_Group">
        @foreach (var item in (IEnumerable<SelectListItem>)ViewBag.AddedThemes)
        {
            <li id="ns@(item.Value)" style="background-color: lightgray;margin-top:50" value="@(item.Value)"> @item.Text</li>
        }
        </ul>
        </div>
        
      
        </td>
      <td id="ThemeNotInGroup" style="min-height:100;min-width:60">
        <div class="editor-field">
       
          <ul id="ThemelstNot_In_Group">
        @foreach (var item in (IEnumerable<SelectListItem>)ViewBag.NonAddedThemes)
        {
            <li id="ns@(item.Value)" style="background-color: lightgray;margin-top:50" value="@(item.Value)"> @item.Text</li>
        }
        </ul>
        
        </div>
        </td></tr>
        </table>*@

    
      
          @*  <div class="editor-label">
            @Html.LabelFor(model => model.CustomerID, "Customer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CustomerID", String.Empty)
            @Html.ValidationMessageFor(model => model.CustomerID)
        </div>*@

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}


 @*<style type="text/css">
        ul
        {
            float: left;
            width: 105px;
            background: silver;
            padding: 10px;
            color: Black;
            margin: 10px;
        }
        ul li
        {
            padding: 5px;
            margin: 5px;
            background-color: white;
            cursor: pointer;
        }
    </style>*@

    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            
            var fn = function (event, ui) {
                $.ajax({
                    url: "@(Url.Action("AddStation", "Grouping", null, "http"))",
                    type: 'POST',
                    context: document.body,
                    data: { stationID: $(ui.draggable[0]).attr('value'), groupID: "@Model.GroupingID" },
                    success: function () {
                           $("#lstIn_Group").append($(ui.draggable[0]).removeAttr("style").attr("style", "background-color: lightgray;margin-top:50"));
                      
                    }
                });
                  $("#lstIn_Group li").draggable();
                    $("#lstNot_In_Group li").draggable();
            };
                var fn1 = function (event, ui) 
                {
                //                $("#lstNot_In_Group").append($(ui.draggable[0]).removeAttr("style"));
           
                      $.ajax({
                    url: "@(Url.Action("RemoveStation", "Grouping", null, "http"))",
                    type: 'POST',
                    context: document.body,
                    data: { stationID: $(ui.draggable[0]).attr('value'), groupID: "@Model.GroupingID" },
                    success: function () {
                             $("#lstNot_In_Group").append($(ui.draggable[0]).removeAttr("style").attr("style", "background-color: lightgray;margin-top:50"));
            
                 
                    }
                    
                });
                             $("#lstIn_Group li").draggable();
                    $("#lstNot_In_Group li").draggable();
            };
            
             var Themefn = function (event, ui) {
                $.ajax({
                    url: "@(Url.Action("AddTheme", "Grouping", null, "http"))",
                    type: 'POST',
                    context: document.body,
                    data: { stationID: $(ui.draggable[0]).attr('value'), groupID: "@Model.GroupingID" },
                    success: function () {
                           $("#ThemelstIn_Group").append($(ui.draggable[0]).removeAttr("style").attr("style", "background-color: lightgray;margin-top:50"));
                      
                    }
                });
                  $("#ThemelstIn_Group li").draggable();
                    $("#ThemelstNot_In_Group li").draggable();
            };
                var Themefn1 = function (event, ui) 
                {
                //                $("#lstNot_In_Group").append($(ui.draggable[0]).removeAttr("style"));
           
                      $.ajax({
                    url: "@(Url.Action("RemoveTheme", "Grouping", null, "http"))",
                    type: 'POST',
                    context: document.body,
                    data: { stationID: $(ui.draggable[0]).attr('value'), groupID: "@Model.GroupingID" },
                    success: function () {
                             $("#ThemelstNot_In_Group").append($(ui.draggable[0]).removeAttr("style").attr("style", "background-color: lightgray;margin-top:50"));
            
                 
                    }
                    
                });
                             $("#ThemelstIn_Group li").draggable();
                    $("#ThemelstNot_In_Group li").draggable();
            };

            $("#lstNot_In_Group li").draggable();
        
            $("#InGroup").droppable({ drop: fn });

            $("#lstIn_Group li").draggable(); // { helper: 'clone' } not good
            $("#NotInGroup").droppable({ drop: fn1 });
            
               $("#ThemelstNot_In_Group li").draggable();
        
            $("#ThemeInGroup").droppable({ drop: Themefn });

            $("#ThemelstIn_Group li").draggable(); // { helper: 'clone' } not good
            $("#ThemeNotInGroup").droppable({ drop: Themefn1 });
            
          
        });
    </script>

    
    <br />
 

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*<script language="javascript" type="text/javascript">


    $(document).ready(function () {

        $("select option").each(function () {
            $(this).draggable({ helper: 'clone' });
        });

      //  $("#lstNot_In_Group").draggable({ helper: 'clone' });
        $("#lstIn_Group").draggable({ helper: 'clone' });
        $("#lstNot_In_Group").droppable({
            accept: ".block",
            activeClass: 'droppable-active',
            hoverClass: 'droppable-hover',
            drop: function (ev, ui) {

                document.getElementById("display").innerHTML = $(ui.draggable).children("li:first").text();

                var lid = ($(ui.draggable).children("li:first"));

                var removeLink = document.createElement("a");
                removeLink.innerHTML = "remove";
                removeLink.href = "#";
                removeLink.onclick = function () {
                    $("#drop1").children().remove("#" + lid[0].id);
                    $(this).remove();
                };
                $(this).append($(ui.draggable).clone().children("li:first").addClass("blocker"));
                $(this).append(removeLink);

            }
        });

    });
    </script>*@


    

Backup/eAd.Website/Views/Grouping/Index.cshtml
@model IEnumerable<eAd.DataAccess.Grouping>

@{
    ViewBag.Title = "Groups";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Name
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.GroupingID }) |
            @Html.ActionLink("Details", "Details", new { id=item.GroupingID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.GroupingID })
        </td>
    </tr>
}

</table>